---
title: "Inference Course Project"
author: "Joe Nguyen"
date: "25 October 2015"
output: html_document
---

This is the project for the statistical inference class. In it, you will use simulation to explore inference and do some simple inferential data analysis. The project consists of two parts:

1. A simulation exercise.
2. Basic inferential data analysis.


## Simulation for Distribution of Means of Exponentials

### Sample Mean

```{r, echo=TRUE}
set.seed(12345)

# Exponential distribution rate parameter
lambda <- 0.2
nSim <- 1000
n <- 40

# Distribution of averages of n (= 40) exponential distributions
datExpAvg <- apply(matrix(rexp(nSim * n, lambda), nSim), 1, mean)

# Histogram, sample mean, theoretical mean
mnSample <- mean(datExpAvg)
mnTheory <- 1/lambda

hist(datExpAvg, main = "Distribution of Mean of 40 Exponentials",
     xlab = "x"
)
abline(v = mnSample, lty = 1, lwd = 5, col = "blue")
abline(v = mnSample, lty = 2, lwd = 5, col = "red")
```


### Sample Variance

```{r, echo=TRUE}


```